function buat_login() {
	let login = document.getElementById("login");
	login.parentElement.removeChild(login);
	var p = document.createElement("p");
	p.className = "tulisan_login";
	p.innerHTML = "Silahkan Mendaftar";
	let element = document.getElementsByTagName("div")[0];
	element.appendChild(p);
	let form = document.createElement("Form");
	element.appendChild(form);
	let label = document.createElement("label");
	label.innerHTML = "Nama User";
	form.appendChild(label);
	let nama = document.createElement("input");
	nama.type = "text";
	nama.name = "username";
	nama.className = "form_login";
	nama.placeholder = "Nama User";
	form.appendChild(nama);
	let label2 = document.createElement("label");
	label2.innerHTML = "Nomor Handphone";
	form.appendChild(label2);
	let input_password = document.createElement("input");
	input_password.type = "tel";
	input_password.className = "form_login";
	input_password.placeholder = "Nomor Handphone";
	form.appendChild(input_password);
	let label3 = document.createElement("label");
	label3.innerHTML = "Username";
	form.appendChild(label3);
	let input_username = document.createElement("input");
	input_username.type = "text";
	input_username.className = "form_login";
	input_username.placeholder = "Username atau Email";
	form.appendChild(input_username);
	let label4 = document.createElement("label");
	label4.innerHTML = "Password";
	form.appendChild(label4);
	let password = document.createElement("input");
	password.type = "password";
	password.className = "form_login";
	password.placeholder = "Password";
	form.appendChild(password);
	let tombol = document.createElement("input");
	tombol.type = "submit";
	tombol.className = "tombol_login";
	tombol.value = "daftar sekarang";
	tombol.style.textTransform = "uppercase";
	form.appendChild(tombol);
}